// Generated by gencpp from file gamecontroller/robocupController_msg.msg
// DO NOT EDIT!


#ifndef GAMECONTROLLER_MESSAGE_ROBOCUPCONTROLLER_MSG_H
#define GAMECONTROLLER_MESSAGE_ROBOCUPCONTROLLER_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gamecontroller
{
template <class ContainerAllocator>
struct robocupController_msg_
{
  typedef robocupController_msg_<ContainerAllocator> Type;

  robocupController_msg_()
    : state(0)
    , penalty(0)  {
    }
  robocupController_msg_(const ContainerAllocator& _alloc)
    : state(0)
    , penalty(0)  {
  (void)_alloc;
    }



   typedef int64_t _state_type;
  _state_type state;

   typedef int64_t _penalty_type;
  _penalty_type penalty;





  typedef boost::shared_ptr< ::gamecontroller::robocupController_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gamecontroller::robocupController_msg_<ContainerAllocator> const> ConstPtr;

}; // struct robocupController_msg_

typedef ::gamecontroller::robocupController_msg_<std::allocator<void> > robocupController_msg;

typedef boost::shared_ptr< ::gamecontroller::robocupController_msg > robocupController_msgPtr;
typedef boost::shared_ptr< ::gamecontroller::robocupController_msg const> robocupController_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gamecontroller::robocupController_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gamecontroller::robocupController_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gamecontroller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'gamecontroller': ['/home/robit/catkin_ws/src/gamecontroller/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gamecontroller::robocupController_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gamecontroller::robocupController_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gamecontroller::robocupController_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gamecontroller::robocupController_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gamecontroller::robocupController_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gamecontroller::robocupController_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gamecontroller::robocupController_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "325ed557b24145c5f42bf6d348873e28";
  }

  static const char* value(const ::gamecontroller::robocupController_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x325ed557b24145c5ULL;
  static const uint64_t static_value2 = 0xf42bf6d348873e28ULL;
};

template<class ContainerAllocator>
struct DataType< ::gamecontroller::robocupController_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gamecontroller/robocupController_msg";
  }

  static const char* value(const ::gamecontroller::robocupController_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gamecontroller::robocupController_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 state\n\
int64 penalty\n\
";
  }

  static const char* value(const ::gamecontroller::robocupController_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gamecontroller::robocupController_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.penalty);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robocupController_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gamecontroller::robocupController_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gamecontroller::robocupController_msg_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.state);
    s << indent << "penalty: ";
    Printer<int64_t>::stream(s, indent + "  ", v.penalty);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAMECONTROLLER_MESSAGE_ROBOCUPCONTROLLER_MSG_H
